### ISSUE TITLE
Issue with example

### ISSUE THREAD

**Issue by kontakt** [codewitch-honey-crisis/htcw_max7219#1]
`using matrix_type = max7219<LCD_WIDTH/8,LCD_HEIGHT/8,PIN_NUM_CS,bus_type,LCD_ROTATION> ;`
should be 
`using matrix_type = max7219<LCD_WIDTH/8,LCD_HEIGHT/8,bus_type,LCD_ROTATION>;`

**Comment by codewitch-honey-crisis** [comment]
Oooh thanks for the catch. I'm rolling out a new revision of GFX soon and I'll have the demo updated when I update this driver. Thanks again! 1.1.0 will have the sample fixed. Old code rears its ugly head!
